services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Inicializa la BD instalando 'base' y sale
  odoo-init:
    image: odoo:18.0
    depends_on:
      - db
    volumes:
      - odoo-data:/var/lib/odoo
      - ./odoo/custom-addons:/mnt/extra-addons
    command: >
      odoo --db_host=db --db_port=5432 --db_user=odoo --db_password=odoo
           -d odoo -i base --load-language=es_ES --without-demo=all --stop-after-init
    restart: "no"

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    environment:
      ODOO_PROXY_MODE: "1"
    ports:
      - "9079:8069"   # si tu panel ignora 'ports:', configura 8069 como HTTP Port en el panel
    volumes:
      - odoo-data:/var/lib/odoo
      - ./odoo/custom-addons:/mnt/extra-addons
    command: >
      odoo --db_host=db --db_port=5432 --db_user=odoo --db_password=odoo
           --database=odoo --http-port=8069 --proxy-mode
    restart: unless-stopped

volumes:
  db-data:
  odoo-data:
