services:
  db:
    image: postgres:15
    container_name: odoo-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:18.0
    container_name: odoo
    depends_on: [db]
    ports:
      - "8079:8069"
    volumes:
      - ./odoo/config:/etc/odoo
      - ./odoo/custom-addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - ADMIN_PASSWORD=MiClaveSuperSegura123
    command: odoo -c /etc/odoo/odoo.conf
    restart: unless-stopped

volumes:
  pgdata:
  odoo-data: