services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
    restart: unless-stopped
    command: >
      bash -lc "python3 -m pip install --no-cache-dir --break-system-packages 'werkzeug==2.3.7'
      && exec /entrypoint.sh odoo"

volumes:
  db-data:
  odoo-data:
